- hosts: test-ubuntu
  vars:
    env_file_location: "{{ lookup( 'ansible.builtin.env', 'SUPABASE_ENV_FILE') }}"
    given_directory: supabase
  tasks:
    - name: Copy environment file to remote host
      ansible.builtin.copy:
        src: "{{ env_file_location }}"
        dest: "{{ ansible_env.PWD }}/docker-compose/{{given_directory}}/.env"
        mode: '0644'  # Optional file permissions
        owner: "{{ sudo_user }}"  # Optional ownership
        group: "{{ sudo_user }}"  # Optional group ownership
        force: no
        backup: true

