- hosts: test-ubuntu
  vars:
    env_file: "{{ lookup( 'ansible.builtin.env', 'SUPABASE_ENV_FILE') }}"
  tasks:
    - name: Print environment file
      ansible.builtin.debug:
        msg: "Environment file path is: {{ env_file }}"
